name: On Template

on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    name: On use template

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Replace if on template
        run: node ./on-template.js

      - name: Commit
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Replace template variables'
          rebase: 'true'
